# Site settings
title:          Research Blog
description:    "HFPsych Lab Research Blog"
baseurl:        "/blog"
url:            "https://humanfactorspsych.github.io"


# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Yoon Kyung Lee
  url:          https://
  email:        yoonkyunglee78@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# remote theme
remote_theme: chesterhow/tale

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
